### ISSUE TITLE
Поправить описание проекта

### ISSUE THREAD

**Issue by FarmV** [it-beard/bloggers-cms#213]
На главное странице в описании написанно 'Платформа позволяет блогкрам aka Брендам вести учёт". Испарвить, букву в слове блогер.  А также обратить внимание на описание "Всё общение с контрибьюторами проекту ведется на..." . Может имелось в виду "Проекта" или "по проекту"?

**Comment by itbeard** [comment]
Спасибо за комментарий, поправил. На будущее - ставь плз проект активный, а то я упустил таску из-за отсутствия проекта :)
