### ISSUE TITLE
Страница "Создание Топика"

### ISSUE THREAD

**Issue by itbeard** [it-beard/bloggers-cms#31]
As a User I want to be able add Topics and then assign Peoples to particular topics
Examples:
- Rust
- Type Script
- AI

Fields
- Id
- Name
- CreatedAt
- UpdatedAt

**Comment by Alex2021cyberhuman** [comment]
Реализовал выбор персон связанных с темой через чекбок-кнопки. Следует ли внедрить сюда фильтрацию персон?
