### ISSUE TITLE
Логирование исключений

### ISSUE THREAD

**Issue by Alex2021cyberhuman** [it-beard/bloggers-cms#79]
Добавить системы диагностики и логирования WebApi

**Comment by Alex2021cyberhuman** [comment]
Готов решить этот вопрос с помощью нлог и фильтров обработки исключений

**Comment by itbeard** [comment]
> 
> 
> Готов решить этот вопрос с помощью нлог и фильтров обработки исключений

в добрый путь

**Comment by Alex2021cyberhuman** [comment]
Сейчас, если пользователь api запросит не существующею сущность он получит ошибку сервера т.к. методы репозиториев возвращают null если сущность не найдена, а mapper пытается преобразовать null в специальный тип response. Я предлагаю выкидывать тип исключений NotFoundException и преобразовывать в спец. тип ответа со статус кодом 404. Так же мне надо переделать предыдущую систему обработки исключений в контроллерах.

**Comment by pingvin1308** [comment]
Учитывая что проект впитывает в себя все модные подходы. То апи следует делать таким, чтобы оно возвращало ошибку с ProblemDetails. Ну и да, при не нахождении сущности можно вернуть 404-ую

**Comment by Alex2021cyberhuman** [comment]
Что должно содержать problem details?

**Comment by pingvin1308** [comment]
в asp.net core есть класс для этого. Это уже своего рода стандарт для апи ошибок.
https://tools.ietf.org/html/rfc7807

**Comment by itbeard** [comment]
SerialLog https://serilog.net

**Comment by itbeard** [comment]
пока не актуально
